# Task 3 : ลองทำ Histogram Equalization

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

## **Step 1 : Create an image**

In [2]:
img = np.array([[5,3,1,0,1],
               [0,2,1,0,5],
               [1,5,0,1,2],
               [4,2,6,2,1],
               [6,2,0,1,5]]
               )
print(img)

[[5 3 1 0 1]
 [0 2 1 0 5]
 [1 5 0 1 2]
 [4 2 6 2 1]
 [6 2 0 1 5]]


## **Step 2 : Histogram Equalization**

### Find the cumulative distribution function (CDF)

Since all the pixels are integers(all pixels are 3-bit (0-7)), we can use the histogram function to find the CDF. The CDF is the sum of the histogram up to a particular bin, normalized to the range [0,1].

In [3]:
hist, bins = np.histogram(img, 8 , [0,8])
print(f'hist = {hist} , bins = {bins}')

hist = [5 7 5 1 1 4 2 0] , bins = [0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [4]:
prop = hist/np.sum(hist)
print(f'prop = {prop}')

prop = [0.2  0.28 0.2  0.04 0.04 0.16 0.08 0.  ]


In [5]:
cdf = prop.cumsum()
print(f'cdf = {cdf}')

cdf = [0.2  0.48 0.68 0.72 0.76 0.92 1.   1.  ]


### Find the transfer function

In [6]:
maxVal = np.max(img)
print(f'maxVal = {maxVal}')
S = np.floor((cdf*maxVal)).astype(int)
print(f'S = {S}')

maxVal = 6
S = [1 2 4 4 4 5 6 6]


### Apply the transfer function to the image

In [7]:
imgnew = S[img]

## **Step 3 : Show the result**

In [8]:
print(f'imgnew = \n {imgnew}')

imgnew = 
 [[5 4 2 1 2]
 [1 4 2 1 5]
 [2 5 1 2 4]
 [4 4 6 4 2]
 [6 4 1 2 5]]
